### ISSUE TITLE
Global style for alert messages

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#28]
Alerts should be based on the USWDS `usa-alert-warning`, with these modifications:

![alert-warning](https://cloud.githubusercontent.com/assets/4106356/20440540/72fc644e-ad75-11e6-9ee2-af96697934e7.png)

With variants for success, warning, error and informational alerts as follows:

<img width="681" alt="screen shot 2016-11-22 at 10 30 58 am" src="https://cloud.githubusercontent.com/assets/4106356/20536644/a6d4903a-b09e-11e6-8e96-8199dd2b218b.png">

**Claim status:**
- Success
  - [ ] [Upload success](https://marvelapp.com/2dh4dia/screen/15297501)
  - [ ] [Request for decision received](https://marvelapp.com/2dh4dia/screen/15297534)
- Warning
  - [ ] [Tracked items alert](https://marvelapp.com/2dh4dia/screen/15297472)
  - [ ] [Requested of others warning](https://marvelapp.com/2dh4dia/screen/15336880)
  - [ ] [Optional evidence warning](https://marvelapp.com/2dh4dia/screen/15297510)
  - [ ] [System downtime message](https://cloud.githubusercontent.com/assets/4106356/20441870/1d6a34d8-ad7b-11e6-90f5-0f8e7be0eb9f.png)
- Error
  - [ ] [Upload error](https://marvelapp.com/2dh4dia/screen/15300483)
- Informational
  - [ ] [Empty claims list](https://marvelapp.com/2dh4dia/screen/15306428)
  - [ ] [Adding claim details](https://marvelapp.com/2dh4dia/screen/15297473)
  - [ ] [Completed claim](https://marvelapp.com/2dh4dia/screen/15297474)
  - [ ] [Request claim decision](https://marvelapp.com/2dh4dia/screen/15297531)

**Prescriptions:**
- Success
  - [ ] [Refill Requested](https://marvelapp.com/2i284g4/screen/16306309)
- Warning 
  - [ ] [Medication list disclaimer](https://marvelapp.com/2i284g4/screen/16306318) See [#269](https://github.com/department-of-veterans-affairs/kudos-team/issues/269)
- Error
  - [ ] [Prescription Refill Unsuccessful](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#3-prescription-refill-unsuccessful)
  - [ ] [Prescription Not Refillable](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#4-prescription-not-refillable)

**Secure messaging:**
- Success
  - [ ] [Sent message](https://marvelapp.com/1bdd199/screen/15044659)
  - [ ] [Deleted draft](https://marvelapp.com/1bdd199/screen/15044660)
  - [ ] [Moved message](https://marvelapp.com/1bdd199/screen/15044690)
  - [ ] [Created a folder](https://marvelapp.com/1bdd199/screen/17079595)
  - [ ] [Deleted a folder](https://marvelapp.com/1bdd199/screen/17079598)
  - [ ] [Deleted a message](https://marvelapp.com/1bdd199/screen/15044660)
  - [ ] [Saved draft](https://marvelapp.com/1bdd199/screen/15044688) 
- Error
  - [ ] [Invalid search](https://marvelapp.com/1bdd199/screen/15055401)
  - [ ] [Triage group errors](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#14-triage-group-errors)
  - [ ] [Unable to move messages](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#15-unable-to-move-message)
  - [ ] [Service errors](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Design/Error-messaging.md#16-service-errors)
- Informational 
  - [ ] [Things you should know](https://marvelapp.com/1bdd199/screen/15044678)

**Education Benefits:**
- Success
- Warning
  - [ ] [Not all forms are in Vets.gov](https://dev.vets.gov/education/apply-for-education-benefits/)
  - [ ] [Key legalese for relinquishment options](https://dev.vets.gov/education/apply-for-education-benefits/application/benefits-eligibility/benefits-relinquishment)
- Error

- Informational
  - [ ] [Progress saving not available](https://dev.vets.gov/education/apply-for-education-benefits/application/introduction)
  - [ ] [About selection](https://dev.vets.gov/education/apply-for-education-benefits/application/benefits-eligibility/benefits-selection)
  - [ ] [Confirmation details](https://dev.vets.gov/education/apply-for-education-benefits/application/submit-message)

**Health Care Application:**
- Warning
  - [ ] [Health Care Apply page warning](https://www.vets.gov/healthcare/apply/) - See [mockup](https://cloud.githubusercontent.com/assets/4106356/20440633/bf72f8b0-ad75-11e6-8027-7c35181ebab4.png)

**Comment by melwoodard** [comment]
Consolidating vets-website issues [#4029](https://github.com/department-of-veterans-affairs/vets-website/issues/4029) and [#4080](https://github.com/department-of-veterans-affairs/vets-website/issues/4080) here
