### ISSUE TITLE
Feature Audit: Cross-app findings

### ISSUE THREAD

**Issue by melwoodard** [department-of-veterans-affairs/vets.gov-patterns#41]
### General layout / structure

- [x] Use of breadcrumbs and/or back links
- [ ] Template variations:
   - Single column
   - Main column + sidebar

### Styling / components

- [ ] Definition cards: different heading levels, colors and hover states
   - [ ] Claim status: `h4.claim-list-item-header` - light blue -> dark blue on hover
   - [ ] Prescriptions: `h3.rx-prescription-title` - dark blue -> light blue + underline on hover
- [ ] Process lists: different heading colors
   - [x] Edu/HCA forms: `#5b616b` (fails 508 check) --> new progress indicator component design
   - [ ] Claim status: `#112e51` (default for H5)
- [x] Headings: inconsistent hierarchy, makes it difficult for users with screenreaders who scan pages by H1, H2, etc. We're implementing headings based on visual style rather than proper hierarchical structure. See [#760](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/760)
